# Workflow
# Should have name

name: Hello
# on tells when the workflow should run
on:
  workflow_dispatch: 

# Jobs
# Should be inside the workflow

#Job tells what the workflow should do, there can be one or more than one job hence we write jobs
#jobs is an object so needs indentation

jobs:
# 1st job - give indentation
  say-hello:
    # creates an ephermal container with ubuntu running
    runs-on: ubuntu-latest
    # That ephermal container will have steps to execute, hence name those steps and use run 
    steps:
      - name: Say hello to everyone
        run: echo "Hello Dosto"

# Steps
# Should be inside a Job

# Actions 
# Should be inside Steps
