name: scheduled tasks

on:
    # schedule:
    #     - cron: '30 2 * * 1'
    #     - cron: '0 */6 * * *'

    workflow_dispatch:

jobs:
    schedule-name:
        runs-on: ubuntu-latest

        steps:
            - name: print the triggered
              run: |
                echo "Workflow triggered by schedule: ${{ github.event.schedule }}"

            - name: Health check using curl
              run: |
                    URL="http://www.google.com"

                    STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" $URL)

                    echo "Response code: $STATUS_CODE"

                    if [ "$STATUS_CODE" -ne 200 ]; then
                        echo "Health check failed!"
                        exit 1
                    fi

                    echo "Health check passed!"

            