name: secret workflow

on:
    workflow_dispatch:

jobs:
    secret:
        runs-on: ubuntu-latest

        steps:
            - name: verify if secret is set
              if: ${{ secrets.MY_SECRET_MESSAGE != '' }}
              run: |
                echo "The secret is set: true"
                


