name: secret workflow

on:
    workflow_dispatch:

jobs:
    secret:
        runs-on: ubuntu-latest

        steps:
            - name: verify if secret is set
              run: |
                if [ "${{ secrets.MY_SECRET_MESSAGE != '' }}" = "true" ]; then
                    echo "The secret is set: true"
                else
                    echo "The secret is set: false"
                fi
                


